from typing import List, Dict
import logging

def validate_response_against_context(response: str, context_chunks: List[Dict]) -> bool:
    """
    Validate that the response is grounded in the provided context.
    
    Args:
        response: The response generated by the LLM
        context_chunks: List of context chunks that were provided to the LLM
        
    Returns:
        True if response is grounded in context, False otherwise
    """
    # Extract context content
    context_content = " ".join([chunk.get('payload', {}).get('content', '') for chunk in context_chunks if 'payload' in chunk])
    
    # Simple heuristic: check if key information in response is present in context
    # This is a basic validation - in a real implementation, you might use more sophisticated NLP techniques
    response_words = set(response.lower().split())
    context_words = set(context_content.lower().split())
    
    # If less than 50% of the response words are in the context, consider it invalid
    if len(response_words) == 0:
        return True  # Empty response is valid
    
    common_words = response_words.intersection(context_words)
    if len(common_words) / len(response_words) < 0.5:
        logging.warning("Response may contain information not present in context")
        return False
    
    return True

def filter_response_by_context(response: str, context_chunks: List[Dict]) -> str:
    """
    Filter the response to ensure it only contains information from the context.
    
    Args:
        response: The response generated by the LLM
        context_chunks: List of context chunks that were provided to the LLM
        
    Returns:
        Filtered response that only contains information from the context
    """
    # For now, we'll return the response as-is, but in the future we could implement
    # more sophisticated filtering to ensure compliance with the context
    return response

def check_for_hallucinations(response: str, context_chunks: List[Dict]) -> bool:
    """
    Check if the response contains hallucinations (information not in the context).
    
    Args:
        response: The response generated by the LLM
        context_chunks: List of context chunks that were provided to the LLM
        
    Returns:
        True if no hallucinations detected, False otherwise
    """
    return validate_response_against_context(response, context_chunks)

def validate_answer_only_mode(query: str, response: str, context_chunks: List[Dict]) -> bool:
    """
    Validate that the response adheres to 'answer only from selected text' mode.
    
    Args:
        query: The original query
        response: The response generated by the LLM
        context_chunks: List of context chunks that were provided to the LLM
        
    Returns:
        True if response adheres to 'answer only' mode, False otherwise
    """
    # Check if the response is grounded in the context
    is_context_valid = validate_response_against_context(response, context_chunks)
    
    # If the response is not grounded in context, check if it appropriately declines
    if not is_context_valid:
        decline_phrases = [
            "cannot answer based on the provided context",
            "i don't have enough information",
            "not mentioned in the context",
            "not found in the provided text"
        ]
        
        response_lower = response.lower()
        for phrase in decline_phrases:
            if phrase in response_lower:
                return True  # Appropriately declined to answer
        
        return False  # Not properly adhering to answer-only mode
    
    return True
